### ISSUE TITLE
When running `auth` command, don't overwrite an existing auth.json file

### ISSUE THREAD

**Issue by ashanan** [dogsheep/pocket-to-sqlite#10]
Ran the `auth` command in the same directory I'd previously set up an auth.json file for `twitter-to-sqlite` and it was completely overwritten.  Not the biggest issue, but still unexpected.  Ideally, for me, the keys would just be added to the existing file, but getting a warning and a chance to back out would be a good solution as well.

**Comment by simonw** [comment]
Agreed, that would be a much better implementation.

**Comment by simonw** [comment]
That was clearly the intention from the description of this issue:
- #4

**Comment by ashanan** [comment]
Thanks!
