### ISSUE TITLE
-a option is used for "--auth" and for "--all"

### ISSUE THREAD

**Issue by fernand0** [dogsheep/pocket-to-sqlite#11]
I'm not sure which option is best, instead of -a -all.

**Comment by fernand0** [comment]
I didn't see there is a PR about this: https://github.com/dogsheep/pocket-to-sqlite/pull/7

**Comment by simonw** [comment]
Great catch, thanks.

I'm going to use it to mean `--auth` - since other tools in the Dogsheep family have the same convention.

 `--all` will be the only way to specify all.

**Comment by simonw** [comment]
Just saw that's what's implemented here already!
- #7
